include:
  - project: viz/ci/gitlabpipelines
    ref: develop
    file: index.yml

pytest:
  extends: .python-pytest
  variables:
    PYTEST_ARGS: -s -v
    PYTEST_COVERAGE_ARGS: --cov=veedrive -s
    APT_PACKAGES: libgl1-mesa-glx ffmpeg ghostscript imagemagick
    VEEDRIVE_LOG_LEVEL: DEBUG
    VEEDRIVE_DB_HOST: mongo
  before_script:
    - cp deploy/ImageMagick-6/policy.xml /etc/ImageMagick-6/
    - export VEEDRIVE_MEDIA_PATH=`pwd`/tests/sandbox_folder
    - echo $VEEDRIVE_MEDIA_PATH
  services:
    - mongo

docker-build-image:
  extends: .build-image-using-kaniko

docker-publish-image:
  extends: .publish-image-using-kaniko
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY/bbp-ou-visualization/veedrive
