include:
  - project: viz/ci/gitlabpipelines
    ref: master
    file: index.yml

pytest:
  extends: .python-pytest
  variables:
    PYTEST_ARGS: -s -v
    PYTEST_COVERAGE_ARGS: --cov=veedrive -s
    APT_PACKAGES: libgl1-mesa-glx ffmpeg ghostscript imagemagick
    VEEDRIVE_LOG_LEVEL: DEBUG
    VEEDRIVE_DB_HOST: postgres
    VEEDRIVE_DB_NAME: postgres
    VEEDRIVE_DB_USERNAME: postgres
    VEEDRIVE_DB_PASSWORD: postgres
    VEEDRIVE_SEARCH_FS_KEEP_FINISHED_INTERVAL: 3
    VEEDRIVE_SEARCH_FS_PURGE_LOOP_INTERVAL: 10
    VEEDRIVE_DEFAULT_HOST: "127.0.0.1"
    POSTGRES_PASSWORD: password
  before_script:
    - cp deploy/ImageMagick-6/policy.xml /etc/ImageMagick-6/
  services:
    - postgres

docker-build-image:
  extends: .build-image-using-kaniko

docker-publish-image:
  extends: .publish-image-using-kaniko
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY/viz/veeone/veedrive
