version: "3"
services:
  backend:
    user: ${BACKEND_USER}
    image:  bbpgitlab.epfl.ch:5050/viz/veeone/veedrive
    environment:
      - VEEDRIVE_MEDIA_PATH=/media/
      - VEEDRIVE_DB_HOST=mongo
      - VEEDRIVE_STATIC_CONTENT_URL=https://${HOSTNAME}:${PUBLIC_PORT}/static
      - VEEDRIVE_CONTENT_URL=https://${HOSTNAME}:${PUBLIC_PORT}/content
      - VEEDRIVE_ORIGIN_WHITELIST=127.0.0.1,10.80.13.24,10.80.13.25,10.80.13.26,10.80.13.30
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ${VEEDRIVE_MEDIA_PATH:-/nfs4/bbp.epfl.ch/media/DisplayWall}:/media
    depends_on:
      - mongo
  nginx:
    user: ${NGINX_USER}
    image: nginx
    ports:
      - "8080:443"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${VEEDRIVE_MEDIA_PATH:-/nfs4/bbp.epfl.ch/media/DisplayWall}:/media/static
      - ssl_volume:/ssl
    depends_on:
     - backend
  mongo:
    image: "mongo:latest"
    volumes:
      -  mongo_volume:/data/db/

volumes:
  ssl_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/letsencrypt
  mongo_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/mongodb/store/volume1
