version: "3"
services:
  backend:
    user: ${BACKEND_USER}
    #build: .
    image:  bbpgitlab.epfl.ch:5050/viz/veeone/veedrive
    environment:
      - VEEDRIVE_MEDIA_PATH=/media/
      - VEEDRIVE_DB_HOST=mongo
      - VEEDRIVE_STATIC_CONTENT_URL=http://localhost:8888/static
      - VEEDRIVE_CONTENT_URL=http://localhost:8888/content
      - VEEDRIVE_ORIGIN_WHITELIST=127.0.0.1,10.80.13.24,10.80.13.25,10.80.13.26,10.80.13.30
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ${VEEDRIVE_MEDIA_PATH:-/nfs4/bbp.epfl.ch/media/DisplayWall}:/media
    depends_on:
      - mongo
  nginx:
    user: ${NGINX_USER}
    image: nginx
    ports:
      - "8888:8080"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      # Different than production because on SSL config
      - ./deploy/nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
      - ${VEEDRIVE_MEDIA_PATH:-/nfs4/bbp.epfl.ch/media/DisplayWall}:/media/static
    depends_on:
     - backend
  mongo:
    image: "mongo:latest"
    volumes:
      -  mongo_volume:/data/db/

volumes:
  mongo_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp
