# Make sure prod.env file is up-to-date as it sets-up several env vars!
version: "3"
services:
  backend:
    user: ${BACKEND_USER}
    image: bbpgitlab.epfl.ch:5050/viz/veeone/veedrive:${VEEDRIVE_IMAGE_TAG:-latest}
    environment:
      - VEEDRIVE_MEDIA_PATH=/media
      - VEEDRIVE_CONTENT_URL=https://${HOSTNAME}:${PUBLIC_PORT}/content
      - VEEDRIVE_STATIC_CONTENT_URL=https://${HOSTNAME}:${PUBLIC_PORT}/static
      - VEEDRIVE_ENVIRONMENT=prod
      - VEEDRIVE_SENTRY_DSN=https://9f266d5dba2449b79cdb49622353bd96@o224246.ingest.sentry.io/6383792
      - VEEDRIVE_SENTRY_SAMPLE_RATE=0.05
      - VEEDRIVE_SENTRY_DEBUG=0
      - VEEDRIVE_DB_NAME=veedrive_prod
      - VEEDRIVE_DB_HOST=postgresql14-users.bbp.epfl.ch
      - VEEDRIVE_DB_USERNAME=veedrive_prod
      - VEEDRIVE_DB_PASSWORD=${VEEDRIVE_DB_PASSWORD}
      - VEEDRIVE_ORIGIN_WHITELIST=127.0.0.1,10.80.13.24,10.80.13.25,10.80.13.26,10.80.13.30
      - HTTP_PROXY=http://bbpproxy.epfl.ch:80/
      - PYTHONUNBUFFERED=1
    volumes:
      - ${HOST_MEDIA_PATH:-/nfs4/bbp.epfl.ch/media/DisplayWall}:/media
  nginx:
    restart: always
    user: ${NGINX_USER}
    image: nginx
    ports:
      - "8080:443"
    volumes:
      - ${HOST_MEDIA_PATH:-/nfs4/bbp.epfl.ch/media/DisplayWall}:/media/
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - type: bind
        source: /etc/letsencrypt/live/${HOSTNAME}/privkey.pem
        target: /ssl/privkey.pem
      - type: bind
        source: /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem
        target: /ssl/fullchain.pem
    depends_on:
     - backend
