version: "3"
services:
  web:
    build: .
    environment:
      - VEEDRIVE_MEDIA_PATH=/app/tests/sandbox_folder
      - VEEDRIVE_DB_HOST=mongo
    ports:
      - "4444:4444"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
